# Generated by Django 2.0.4 on 2018-04-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip地址')),
            ],
            options={
                'verbose_name_plural': 'IP扫描结果',
                'verbose_name': 'IP扫描结果',
            },
        ),
        migrations.CreateModel(
            name='PortResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=10, verbose_name='端口')),
                ('service', models.CharField(max_length=50, verbose_name='服务')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.IPResult')),
            ],
            options={
                'verbose_name_plural': '端口结果',
                'verbose_name': '端口结果',
            },
        ),
        migrations.CreateModel(
            name='ScanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanname', models.CharField(max_length=50, verbose_name='扫描项目名')),
                ('scanIP', models.CharField(max_length=100, verbose_name='扫描IP段')),
                ('status', models.BooleanField(default=False, verbose_name='扫描状态')),
                ('process', models.IntegerField(default=0, verbose_name='扫描进度')),
            ],
            options={
                'verbose_name_plural': '扫描项目',
                'verbose_name': '扫描项目',
            },
        ),
        migrations.AddField(
            model_name='ipresult',
            name='scannitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.ScanItems'),
        ),
    ]
