# Generated by Django 2.0.4 on 2018-04-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0002_scanitems_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default='eaafbf7e-cf34-4edf-8372-6f30c34cefc1', max_length=50, verbose_name='任务编号'),
        ),
    ]
