# Generated by Django 2.0.4 on 2018-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0003_scanitems_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default='227c77cf-bd24-4cb0-848b-b3d0ce8de053', max_length=50, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='scanitems',
            name='scanname',
            field=models.CharField(max_length=50, unique=True, verbose_name='扫描项目名'),
        ),
    ]
