# Generated by Django 2.0.4 on 2018-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0005_auto_20180409_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default='63e79fcc-f83b-4dcc-8255-fb422ae29602', max_length=50, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='scanitems',
            name='scanIP',
            field=models.CharField(max_length=100, unique=True, verbose_name='扫描IP段'),
        ),
    ]
