# Generated by Django 2.0.4 on 2018-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0007_auto_20180410_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default='8507e1b5-877f-428d-974a-af661534bfdd', max_length=50, unique=True, verbose_name='任务编号'),
        ),
    ]
