# Generated by Django 2.0.4 on 2018-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0008_auto_20180412_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default='adde8bf8-cff2-4201-ba55-530f39ea7c51', max_length=50, unique=True, verbose_name='任务编号'),
        ),
    ]
