# Generated by Django 2.0.4 on 2018-04-12 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0010_auto_20180412_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanitems',
            name='itemid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='任务编号'),
        ),
    ]
